### ISSUE TITLE
Running react native on ios failing

### ISSUE THREAD

**Issue by BjoernRave** [chen-rn/CUA#11]
When trying to run `yarn native` and then pressing `i` for iOS, I get the following error:
```
iOS Bundling failed 14290ms
error: Error: While resolving module `next/router`, the Haste package `next` was found. However the module `router` could not be found within the package. Indeed, none of these files exist:

  * `/Users/bjoern/projects/farmer-assistant-2/apps/next/router(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)`
  * `/Users/bjoern/projects/farmer-assistant-2/apps/next/router/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)`
    at resolveHasteName (/Users/bjoern/projects/farmer-assistant-2/node_modules/metro-resolver/src/resolve.js:198:9)
    at Object.resolve (/Users/bjoern/projects/farmer-assistant-2/node_modules/metro-resolver/src/resolve.js:68:20)
    at ModuleResolver.resolveDependency (/Users/bjoern/projects/farmer-assistant-2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:126:31)
    at DependencyGraph.resolveDependency (/Users/bjoern/projects/farmer-assistant-2/node_modules/metro/src/node-haste/DependencyGraph.js:264:43)
    at Object.resolve (/Users/bjoern/projects/farmer-assistant-2/node_modules/metro/src/lib/transformHelpers.js:170:21)
    at resolveDependencies (/Users/bjoern/projects/farmer-assistant-2/node_modules/metro/src/DeltaBundler/graphOperations.js:466:33)
    at processModule (/Users/bjoern/projects/farmer-assistant-2/node_modules/metro/src/DeltaBundler/graphOperations.js:232:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async addDependency (/Users/bjoern/projects/farmer-assistant-2/node_modules/metro/src/DeltaBundler/graphOperations.js:361:18)
    at async Promise.all (index 2)
```

**Comment by chen-rn** [comment]
oh, might be a new bug introduced, looking into this

**Comment by chen-rn** [comment]
Fixed in the newest commit!

A couple days ago I changed our next app name from next-app to next so that the folder name and the package name is consistent. For the sake of deploying to Vercel.

Which created a conflict of namespace between "next" the node_modules framework and "next" our web app.

Should've saw that coming! Let me know if it works for you guys now.

**Comment by BjoernRave** [comment]
just tried it and it works :) Thanks for the quick fix
