### ISSUE TITLE
Asking for help - removing tamagui [FEATURE]

### ISSUE THREAD

**Issue by doruksahin** [chen-rn/CUA#64]
**Is your feature request related to a problem? Please describe.**
When i delete everything about tamagui, i get an error. 
I am providing error at the bottom.
Do you have any clue? I just wanted to use nativewind :D

Am i missing something about next 13? But, i ONLY deleted tamagui related settings and wiped out ui folder. It doesn't make sense...

I can provide a repo too, if you consider helping me :( 
Thanks in advance! 
(btw, i was convinced about tamagui by you, however it looks so "verbose" in code and i didnt want to leave tailwind and use a bleeding edge technology...)

```
nextjs:dev: wait  - compiling...
nextjs:dev: error - ../../node_modules/react-native/Libraries/EventEmitter/RCTDeviceEventEmitter.js
nextjs:dev: Module parse failed: Unexpected token (12:12)
nextjs:dev: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
nextjs:dev: |
nextjs:dev: | import EventEmitter from '../vendor/emitter/EventEmitter';
nextjs:dev: > import type {IEventEmitter} from '../vendor/emitter/EventEmitter';
nextjs:dev: |
nextjs:dev: | // FIXME: use typed events
nextjs:dev:
nextjs:dev: Import trace for requested module:
nextjs:dev: ../../node_modules/react-native/Libraries/EventEmitter/RCTDeviceEventEmitter.js
nextjs:dev: ../../node_modules/expo-modules-core/build/SyntheticPlatformEmitter.js
nextjs:dev: ../../node_modules/expo-modules-core/build/index.js
nextjs:dev: ../../node_modules/expo-constants/build/Constants.js
nextjs:dev: ../../packages/app/utils/trpc.tsx
nextjs:dev: ../../packages/app/provider/trpc/index.tsx
nextjs:dev: ../../packages/app/provider/index.tsx

```

**Comment by albbus-stack** [comment]
I've created a new branch in my fork in which I removed tamagui and added tailwind. It doesn't work and it throws a different error: 
```nextjs:build: D:\CUA\node_modules\react-native\index.js:14
nextjs:build: import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
nextjs:build: ^^^^^^
nextjs:build:
nextjs:build: SyntaxError: Cannot use import statement outside a module
nextjs:build:     at internalCompileFunction (node:internal/vm:73:18)
nextjs:build:     at wrapSafe (node:internal/modules/cjs/loader:1176:20)
nextjs:build:     at Module._compile (node:internal/modules/cjs/loader:1218:27)
nextjs:build:     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
nextjs:build:     at Module.load (node:internal/modules/cjs/loader:1117:32)
nextjs:build:     at Module._load (node:internal/modules/cjs/loader:958:12)
nextjs:build:     at Module.require (node:internal/modules/cjs/loader:1141:19)
nextjs:build:     at require (node:internal/modules/cjs/helpers:110:18)
nextjs:build:     at 36182 (D:\CUA\apps\nextjs\.next\server\pages\_document.js:26:47)
nextjs:build:     at __webpack_require__ (D:\CUA\apps\nextjs\.next\server\webpack-runtime.js:25:43)
nextjs:build:
nextjs:build: > Build error occurred
nextjs:build: Error: Failed to collect page data for /signup/email-verification
nextjs:build:     at D:\CUA\node_modules\next\dist\build\utils.js:960:15
nextjs:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
nextjs:build:   type: 'Error'
nextjs:build: }
nextjs:build: ERROR: command finished with error: command (D:\CUA\apps\nextjs) yarn run build exited (1)```

Could you try cloning my branch with `git clone -b nativewind --single-branch https://github.com/albbus-stack/CUA` and seeing the differences with yours?

**Comment by tanjunior** [comment]
I am also exploring the idea of replacing tamagui with shadcn-ui.
